method: vanilla
seed: [0, 1, 2, 3, 4, 5, 6, 7]

env:
  id: BipedalWalker-v3
  vec_envs: 8
  discrete_actions: false
  async_vector: true

ppo:
  steps_per_update: 256
  kl_stop: 0.03

intrinsic:
  eta: 0.0

logging:
  csv_interval: 10000
  checkpoint_interval: 300000

exp:
  total_steps: 3000000
  deterministic: false
